<a href="https://colab.research.google.com/github/nikitask14/neural-networks-pytorch-from-first-principles/blob/main/01_tensors_shapes_datatypes_devices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For one neuron in a layer of a NN, we wrote weighted sum like:

$$ \mathbf z=W\mathbf x+\mathbf b $$

That equation requires us to store and manipulate a lot of numbers:

$$ \mathbf x= \begin{bmatrix} x_1\\x_2\\x_3 \end{bmatrix} $$

and perhaps

$$ W= \begin{bmatrix} w_{11}&w_{12}&w_{13}\\ w_{21}&w_{22}&w_{23} \end{bmatrix} $$

A neural network is therefore doing huge amounts of numerical computation with vectors, matrices, and eventually higher-dimensional collections of numbers.

Ordinary Python can store numbers

In [1]:
[1, 2, 3]

[1, 2, 3]

But a normal Python list was not designed specifically for fast linear algebra, GPU computation, or neural-network gradient calculations.

That is where PyTorch enters. PyTorch provides the machinery needed for Neural Network computations.

***The basic numerical object/data structure PyTorch works with is a tensor***

In [2]:
import torch

No error = PyTorch imported successfully.

In [3]:
scalar = torch.tensor(5)
scalar

tensor(5)

What this says:

1. torch.tensor(...) → ask PyTorch to create a tensor
2. 5 = the numerical data inside it
3. scalar = store that tensor under the name scalar
4. ***scalar***  ask Colab to display it

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

ndinm stands for number of dimensions
1. **ndim** → how many dimensions
2. **shape** → size along each dimension

In [6]:
vector = torch.tensor([7, 5, 3])
vector

tensor([7, 5, 3])

1. torch.tensor created a 1-D PyTorch Tensor containing 3 integer values.
2. [7, 5, 3] is the data we are putting inside it.
3. Storing the tensor in the variable vector.
4. displaying vector.

In [7]:
print(vector.ndim)
print(vector.shape)


1
torch.Size([3])


In [8]:
matrix = torch.tensor([
    [1,2],
    [3,4],
    [5,6]

])
print(matrix)
print(matrix.ndim)
print(matrix.shape)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [9]:
tensor3d = torch.tensor([
    [
        [6,7],
        [8,9],
        [10,11]
    ],
    [
        [12,13],
        [14,15],
        [16,17]
    ]
])
print(tensor3d)
print(tensor3d.ndim)
print(tensor3d.shape)

tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])
3
torch.Size([2, 3, 2])


***dtype*** matters because it controls things like:

1. how much memory each value uses
2. what range/precision the values can represent
3. which mathematical operations make sense

For neural networks, the most important point is this:

Weights and gradients usually need floating-point numbers, because learning depends on small continuous changes like \(0.003\), \(1.27\), \(-0.0004\), not just whole numbers.

In [10]:
x = torch.tensor([1 ,2 ,3])
y = torch.tensor([1.0, 2.0, 3.0])
print(x.dtype)
print(y.dtype)


torch.int64
torch.float32


***torch.int64*** means integer values represented using 64 bits.

***torch.float32*** means floating-point values represented using 32 bits.

shape = how the values are arranged
	​

dtype = what kind of numerical values are stored
	​


In [11]:
x = torch.tensor([1, 2, 3], dtype = torch.float32)

Even though the values look like integers, PyTorch stores them as floating-point numbers.

Why do we need this?

For example, imagine these are feature values:

[18, 25, 40]

They may represent ages, so whole numbers make sense as raw data.

But once those values enter a neural network, they may be multiplied by weights like:

$$ 0.37,\quad -0.12,\quad 1.08 $$

So we may explicitly tell PyTorch:

“Store these input values as floating-point numbers because they are going into floating-point computation.”

That is what dtype = torch.float32 gives us control over how the tensor is represented, independent of how the original numbers were written.

In [12]:
ages = torch.tensor([18, 25, 40], dtype = torch.float32)
print(ages)
print(ages.dtype)

tensor([18., 25., 40.])
torch.float32


In [13]:
ages.device

device(type='cpu')

A tensor’s device tells PyTorch where that tensor is physically stored and where calculations involving it should be carried out.

So if a tensor lives on the CPU:

$$ \text{tensor} \rightarrow \text{CPU computation} $$

If it lives on a GPU:
$$ \text{tensor} \rightarrow \text{GPU computation} $$

Why is GPU useful for neural networks? Because NN training involves enormous numbers of very similar numerical operations — especially matrix multiplications. GPUs are designed to perform many such operations in parallel, so they can be much faster.

There is one very important practical rule:

Tensors involved in the same operation generally need to be on the same device.

In [15]:
torch.cuda.is_available()

False

So read that line as:

“PyTorch, is a CUDA-capable GPU available to me?”

The next device idea is simply moving a tensor.

In [18]:
ages.to("cpu")
ages.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

Because our runtime currently has no GPU,  .to("cuda"); it would fail

TASK:
Create a 2-D tensor named features with:

1. 2 inner lists
2. 3 values in each inner list
3. floating-point datatype

Then print:

the tensor
1. ndim
2. shape
3. dtype
4. device

In [21]:
features = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype = torch.float32)

print(features)
print(features.ndim)
print(features.shape)
print(features.dtype)
print(features.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
2
torch.Size([2, 3])
torch.float32
cpu
