<a href="https://colab.research.google.com/github/nikitask14/neural-networks-pytorch-from-first-principles/blob/main/02_tensor_operations_and_shape_compatibility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch

In [25]:
A = torch.tensor([
    [2, 4, 6],
    [1, 3, 5]
    ])
print(A)
print(A.shape)
print(A.ndim)


tensor([[2, 4, 6],
        [1, 3, 5]])
torch.Size([2, 3])
2


In [26]:
B = torch.tensor([
    [10, 20, 30],
    [2, 4, 6]
])
print(B)
print(B.shape)
print(B.ndim)

tensor([[10, 20, 30],
        [ 2,  4,  6]])
torch.Size([2, 3])
2


Adding tensors A and B element-wise nd print their shape.

In [27]:
tensor_add = A + B
print(tensor_add)

print(tensor_add.shape)


tensor([[12, 24, 36],
        [ 3,  7, 11]])
torch.Size([2, 3])


Element-wise multiplication of tensors A and B

In [28]:
tensor_mul = A * B
print(tensor_mul)
print(tensor_mul.shape)

tensor([[ 20,  80, 180],
        [  2,  12,  30]])
torch.Size([2, 3])


1. **Operation:** Element-wise multiplication
2. **PyTorch:** A * B
3. **Meaning:** corresponding elements multiply


In [29]:
C = torch.tensor([
    [10, 20],
    [30, 40]
])
print(C.shape)

A+C

torch.Size([2, 2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

We had:

$$ A.shape=(2,3) $$

and

$$ C.shape=(2,2) $$

Error says:

The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

For a 2-D tensor with shape (2, 3):

1. dimension 0 → rows → size 2
2. dimension 1 → columns → size 3

So PyTorch compares:

$$ \begin{array}{c|cc} & \text{dim 0} & \text{dim 1}\\ \hline A & 2 & 3\\ C & 2 & 2 \end{array} $$

Dimension 0 matches:

$$ 2=2 \quad \checkmark $$

Dimension 1 does not:

$$ 3\neq2 \quad \times $$

That is exactly what the error is telling us.

**Broadcasting means:**

Can the smaller tensor be reused along a missing or size-1 direction so that the operation makes sense?

For example:

$$ (2,3) + (2,2) $$

failed because neither tensor can sensibly be repeated to make the mismatching 3 and 2 line up.

But:

$$ (2,3) + (3,) $$

works because the (3,) tensor fits naturally across the 3 columns and can be reused for both rows.

Broadcasting — Clean Summary

Broadcasting allows PyTorch to perform element-wise operations on tensors with different shapes when their dimensions are compatible.

Broadcasting compatibility rule
Step 1 — Right-align the shapes

Compare shapes from the rightmost dimension moving left.

Example:

$$ (6,4) $$

and

$$ (4,) $$

Right-align them:

$$ \begin{array}{cc} 6&4\\ 1&4 \end{array} $$

If one tensor has fewer dimensions, imagine adding leading 1s on the left.

Step 2 — Check every aligned dimension pair

For each aligned pair, the sizes are compatible if:

$$ \boxed{\text{they are equal} \quad \mathbf{OR} \quad \text{one of them is }1} $$
Step 3 — Every pair must pass

Broadcasting works only if all aligned dimension pairs are compatible.

So:

$$ \boxed{ \text{Every pair must satisfy: equal OR one is 1} } $$

If even one pair fails, the whole operation fails.

Why does 1 matter?

A dimension of size 1 means there is only one value or slice in that direction.

PyTorch can reuse that single value across the larger dimension.

For example:

$$ (5,3)+(1,3) $$

The single row can be reused across 5 rows.

Examples
Example 1
$$ (5,3)+(5,3) $$
3 vs 3 → equal
5 vs 5 → equal

Works.

Example 2
$$ (5,3)+(1,3) $$
3 vs 3 → equal
5 vs 1 → one is 1

Works.

Example 3
$$ (5,3)+(5,1) $$
3 vs 1 → one is 1
5 vs 5 → equal

Works.

Example 4
$$ (5,3)+(3,) $$

Right-align:

$$ \begin{array}{cc} 5&3\\ 1&3 \end{array} $$
3 vs 3 → equal
5 vs 1 → one is 1

Works.

Example 5
$$ (5,3)+(5,) $$

Right-align:

$$ \begin{array}{cc} 5&3\\ 1&5 \end{array} $$
3 vs 5 → not equal and neither is 1

Fails.

Example 6
$$ (2,5,3)+(5,1) $$

Right-align:

$$ \begin{array}{ccc} 2&5&3\\ 1&5&1 \end{array} $$
3 vs 1 → Pass
5 vs 5 → Pass
2 vs 1 → Pass

Works.

Important points
Broadcasting compares shapes from right to left.
Missing dimensions are treated as leading 1s on the left.
Tensors do not need to have the same number of dimensions.
For each aligned pair: equal OR one is 1.
Across the whole shape: every aligned pair must pass.
A dimension of size 1 is called a singleton dimension.
Broadcasting is heavily used in neural networks, especially when adding biases to batches of activations.
Mental model

Right-align → compare every pair → equal or 1 → every pair must pass.

In [ ]:
A = torch.tensor([
    [1,2,3],
    [4,5,6]
])

B = torch.tensor(
    [10, 20,30]
)
tensor_add1 = A+B
print(tensor_add1)
print(tensor_add1.shape)


In [ ]:
C = torch.tensor([
    [20],
    [40]
])

D = torch.tensor([
    [21, 31, 41]
])
tensor_add2 = C+D
print(tensor_add2)
print(tensor_add2.shape)

**Matrix - multiplication in PyTorch**

In [ ]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

B = torch.tensor([
    [10, 20],
    [30, 40],
    [50, 60]
])

print(A.shape)
print(B.shape)

Performing matrix multiplication using matmul

In [ ]:
matmul = torch.matmul(A,B)
print(matmul)
print(matmul.shape)

In [ ]:
A@B

In [ ]:
uncompatible_tensor = torch.tensor([
    [6, 12],
    [18, 24],
    [30, 36],
    [42, 48]
])
uncompatible_tensor.shape

In [ ]:
A@uncompatible_tensor

**Neural-network connection**

This sitting has now given us the tensor mechanics behind operations we meet when we implemenrt the NNs:

**$$ XW+b $$**
1. \(XW\) → matrix multiplication
2. \(+b\) → often uses broadcasting
all of these operations depend on understanding tensor shapes

That connection becomes very important once we start building actual layers.