<a href="https://colab.research.google.com/github/nikitask14/neural-networks-pytorch-from-first-principles/blob/main/Linear_Regression_with_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: Setting up a small Regression Problem**

Our dataset is:

$$ \begin{array}{c|c} x & y\\ \hline 1&3\\ 2&5\\ 3&7\\ 4&9 \end{array} $$

We have four labelled training examples. Each example has one feature and one target.


In [54]:
import torch

In [55]:
x = torch.tensor([1,2, 3, 4], dtype = torch.float32)
print(x)
print(x.dtype)
print(x.ndim)
print(x.shape)

tensor([1., 2., 3., 4.])
torch.float32
1
torch.Size([4])


In [56]:
y = torch.tensor([3, 5, 7, 9], dtype = torch.float32)
print(y)
y.dtype

tensor([3., 5., 7., 9.])


torch.float32

**Step 2:** define the model parameters and make predictions.

In [57]:
# Initialize weight and bias with gradients enabled
w = torch.tensor(0.0, requires_grad = True)
b = torch.tensor(0.0, requires_grad = True)





In [ ]:
y_hat = w * x + b
print(y_hat)

**Why no loop is needed:**


x is a 1D tensor of shape (4,), while w and b are scalar tensors. PyTorch broadcasts the scalar values across all elements of x, so
$$y_hat = w * x + b$$
computes all four predictions at once:

$$ [wx_1+b,\ wx_2+b,\ wx_3+b,\ wx_4+b] $$

This is a vectorized tensor operation, so an explicit Python loop is unnecessary.

**Step 3: Compute Loss**

In [38]:
squared_error = (y_hat - y) ** 2
print(squared_error)
loss = squared_error.mean()
print(loss)


tensor([ 9., 25., 49., 81.], grad_fn=<PowBackward0>)
tensor(41., grad_fn=<MeanBackward0>)



squared_error = (y_hat - y) ** 2

creates the four individual squared errors:

$$ [9,\ 25,\ 49,\ 81] $$

Then:

**loss = squared_error.mean()**

takes their average:

$$ \frac{9+25+49+81}{4} = \frac{164}{4} = 41 $$


**tensor(41., grad_fn= MeanBackward0>)**

The grad_fn is there because this loss ultimately depends on our tracked parameters w and b.



**Step 4: One full training Step**

In [25]:
loss.backward()
print(w.grad)
print(b.grad)

tensor(-35.)
tensor(-12.)


Since dLoss/dw is negative, it means increasing weight would reduce loss. This makes sense, as both w and b are 0 right now.

In [26]:
lr = 0.01

with torch.no_grad():
  w -= lr * w.grad
  b -= lr * b.grad

print(w)
print(b)


tensor(0.3500, requires_grad=True)
tensor(0.1200, requires_grad=True)


In [30]:
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor(0.)
tensor(0.)


Conceptually:

All 4 examples
      ->
 predictions
       ->
loss
      ->
gradients
       ->
update w,b
      ->
All 4 examples again
       ->
new predictions
       ->
new loss
       ->
new gradients
       ->
update w,b again
       ->
...

Each complete pass through the training data is what we call an epoch.

**Repeated training loop **

In [61]:
x = torch.tensor([1,2, 3, 4], dtype = torch.float32)
y = torch.tensor([3, 5, 7, 9], dtype = torch.float32)
# Initialize weight and bias with gradients enabled
w = torch.tensor(0.0, requires_grad = True)
b = torch.tensor(0.0, requires_grad = True)

for _ in range(100):
  y_hat = w * x + b
  squared_error = (y_hat - y) ** 2
  loss  = squared_error.mean()


  loss.backward()
  lr = 0.01

  with torch.no_grad():
    w -= lr * w.grad
    b -= lr * b.grad

  w.grad.zero_()
  b.grad.zero_()

print(w.grad)
print(b.grad)
print(w)
print(b)
print(loss)

tensor(0.)
tensor(0.)
tensor(2.0722, requires_grad=True)
tensor(0.7876, requires_grad=True)
tensor(0.0076, grad_fn=<MeanBackward0>)
